on homer

diff --git a/irc/xchat_sh_plugin/xchat_sh_scripts/b0t/invite b/irc/xchat_sh_plugin/xchat_sh_scripts/b0t/invite
--- a/irc/xchat_sh_plugin/xchat_sh_scripts/b0t/invite
+++ b/irc/xchat_sh_plugin/xchat_sh_scripts/b0t/invite
@@ -1,4 +1,29 @@
-alias double_escape_slashes=" sed 's+\\\\+\\\\\\\\\\\\\\\\+g' "
+#!/bin/bash
+
+double_escape_slashes () {
+	sed 's+\\+\\\\\\\\+g'
+}
+
+# if [ "$CHANNEL" = "#ctf.pug" ]
+# then
+	# (
+		# if [ "$HASVOICE" ] || [ "$HASOP" ]
+		# then
+			# target="$1"
+			# if [ "$target" ]
+			# then
+				# # . restrict_repetitive_calls "5 minutes"
+				# echo "/invite $target #ctf.pug"
+				# echo "/notice $NICK I have invited $target"
+			# else
+				# echo "/notice $NICK Invite who?"
+			# fi
+		# else
+			# : # echo "/notice $NICK You need voice to !invite players"
+		# fi
+	# ) | double_escape_slashes
+	# exit 0
+# fi
 
 # if [ ! "$CHANNEL" = "#noobpug" ] && [ ! "$CHANNEL" = "#ut" ]
 # then exit 0
@@ -16,22 +41,30 @@ then
 			echo "/msg tOmy\` [$NICK requested an invite for $* in $CHANNEL]"
 			echo "/msg [eC]Rednas [$NICK requested an invite for $* in $CHANNEL]"
 			echo "/msg nogginBasher [$NICK requested an invite for $* in $CHANNEL]"
-                        echo "/msg BADMF [$NICK requested an invite for $* in $CHANNEL]"
+			echo "/msg BADMF [$NICK requested an invite for $* in $CHANNEL]"
 			echo "/msg #pug.up.admins [$NICK requested an invite for $* in $CHANNEL]"
-                        exit
+			exit
 		elif [ "$CHANNEL" = "#ut.pug" ]
 		then
 			# echo "[$CHANNEL is not accepting new invites at this time.]"
+			echo "/invite $* #pug.up"
+			# echo "/msg BADMF [$NICK has requested an invite for $* to #ut.pug]"
+			# echo "/msg flakkbunz0r [$NICK has requested an invite for $* to #ut.pug]"
+			# echo "/msg $NICK I have invited $* to #pug.up for you :)  Also I PMed BADMF and flakkbunz0r (the other admins blocked botspam)."
+			# echo "/notice $NICK I tried to message BADMF and flakkbunz0r about your invite request."
+			# echo "/notice $NICK I could not forward your invite request because I don't know the nicks of the admins!"
+			echo "/notice $NICK I am not actually allowed to invite your friend to #ut.pug =/"
+			echo "/notice $NICK I recommend you PM one of the fasci^H^H^H^H^Hadmins instead."
+			echo "/msg nogginBasher [$NICK has requested an invite for $* to #ut.pug]"
 			exit
-			echo "[Your request to invite $* has been forwarded to #ut.admins (probably)]"
-			echo "/msg #ut.admins [$NICK is requesting an invite for $*]"
-			echo "/msg LiquidFire [$NICK is requesting an invite for $* to #ut.pug]"
-			echo "/msg Majinx [$NICK is requesting an invite for $* to #ut.pug]"
+			# echo "[Your request to invite $* has been forwarded to #ut.admins (probably)]"
+			# echo "/msg #ut.admins [$NICK is requesting an invite for $*]"
+			# echo "/msg Nin] [$NICK has requested an invite for $* to #ut.pug]"
+			# echo "/msg LiquidFire [$NICK is requesting an invite for $* to #ut.pug]"
+			# echo "/msg Majinx [$NICK is requesting an invite for $* to #ut.pug]"
 			# echo "/msg [SMo]Vader [$NICK is requesting an invite for $* to #ut.pug]"
-			echo "/msg BADMF [$NICK is requesting an invite for $* to #ut.pug]"
-			echo "/msg nogginBasher [$NICK is requesting an invite for $* to #ut.pug]"
-			echo "/msg off|noggin [$NICK is requesting an invite for $* to #ut.pug]"
-			echo "/msg nB^ [$NICK is requesting an invite for $* to #ut.pug]"
+			# echo "/msg off|noggin [$NICK is requesting an invite for $* to #ut.pug]"
+			# echo "/msg nB^ [$NICK is requesting an invite for $* to #ut.pug]"
 		fi
 	else
 		echo "Usage: !invite <nick>"
@@ -39,15 +72,17 @@ then
 	exit
 fi
 
-[ "$CHANNEL" = "#adl.pvt" ]
-if [ "$CHANNEL" = "#noobpug" ] || [ "$CHANNEL" = "#smo.priv" ] || [ "$CHANNEL" = "#chillmunks.priv" ] || echo "$NICK" | grep -i "^goly" >/dev/null || echo "$NICK" | grep -i "^mox" >/dev/null || echo "$NICK" | grep -i "mox$" >/dev/null || echo "$NICK" | grep -i "^[|]*sandwich[|]*$" >/dev/null || echo "$NICK" | grep -i "^[|]*xaz[|]*$" >/dev/null || echo "$NICK" | grep -i "^evi" >/dev/null
+# [ "$CHANNEL" = "#adl.pvt" ]
+if [ "$CHANNEL" = "#noobpug" ] || [ "$CHANNEL" = "#nzp" ] || [ "$CHANNEL" = "#smo.priv" ] || [ "$CHANNEL" = "#chillmunks.priv" ] || echo "$NICK" | grep -i "^goly" >/dev/null || echo "$NICK" | grep -i "^mox" >/dev/null || echo "$NICK" | grep -i "mox$" >/dev/null || echo "$NICK" | grep -i "^[|]*sandwich[|]*$" >/dev/null || echo "$NICK" | grep -i "^[|]*xaz[|]*$" >/dev/null || echo "$NICK" | grep -i "^evi" >/dev/null || [ "$AUTH" = "nogginBasher" ]
 then
 	if [ "$1" ]
 	then NICK="$1"
 	fi
-	echo "/invite $NICK #ut.pug"
-	echo "/invite $NICK #noobpug"
-	echo "/invite $NICK #pug.up"
+	(
+		echo "/invite $NICK #ut.pug"
+		echo "/invite $NICK #noobpug"
+		echo "/invite $NICK #pug.up"
+	) | double_escape_slashes
         # if [ "$1" ]
 	# then echo "/invite $1 #ut.pug"
 	# fi
@@ -64,66 +99,74 @@ then
 	exit
 fi
 
-(
 if [ "$CHANNEL" = "#pug.up.admins" ]
 then
-        if [ "$1" = "help" ] || [ "$1" = "-h" ]
-	then
-            echo "$COLRED$COLBOLD .invite <nick> <trial/register>"
+
+	(
+
+		## The exit commands inside this (...) block do not affect the outer script.
+
+		if [ "$1" = "help" ] || [ "$1" = "-h" ]
+		then
+			echo "$COLRED$COLBOLD .invite <nick> <trial/register>"
+			exit
+		fi
+
+		if [ "$2" = "register" ]
+		then
+			echo "/msg Q chanlev #pug.up $1 +gv"
+			echo "$COLRESET I have invited $COLRED$COLBOLD $1 $COLRESET to #pug.up and also attempted to $COLBOLD register $COLRESET him with +gv"
+			echo "/invite $1 #pug.up"
+			echo "$COLPINK Sending Explanation to $COLRED$COLBOLD $1 $COLPINK..."
+			echo "/msg $1 $COLBOLD U have been invited to join #pug.up"
+			echo "/msg $1 $COLBOLD In order to keep unwanted people out, #pug.up is an invite-only channel."
+			echo "/msg $1 $COLBOLD If you are authed atm i registered u to the channel with +gv."
+			echo "/msg $1 $COLBOLD From now on u can invite urself to the pug channel with the following commands:"
+			echo "/msg $1 $COLRED$COLBOLD /msg Q invite #pug.up"
+			echo "/msg $1 $COLBOLD /join #pug.up"
+			echo "/msg $1 $COLBOLD Alternatively, you can set your own +j flag on the channel, which will cause you to be auto-invited whenever you auth: /msg Q chanlev #pug.up $1 +j"
+			echo "/msg $1 $COLBOLD If you need an auth account, then you need to type: /msg Q HELLO <your_email> <your_email>"
+			echo "/msg $1 $COLBOLD If i failed to register u properly contact the admins for support: BADMF, amok, teasy, tomy, nogginbasher"
+			echo "/msg $1 $COLGREEN$COLBOLD Enjoy puggin !"
+			echo "$COLPINK ... done"
+			exit
+		fi
+
+		if [ "$2" = "trial" ]
+		then
+			echo "/msg Q chanlev #pug.up $1 +k"
+			echo "$COLRESET I have invited $COLRED$COLBOLD $1 $COLRESET to #pug.up and also attempted to $COLBOLD register $COLRESET him as $COLGREEN$COLBOLD trial $COLRESET with +k"
+			echo "/invite $1 #pug.up"
+			echo "$COLPINK Sending Explanation to $COLRED$COLBOLD $1 $COLPINK..."
+			echo "/msg $1 $COLBOLD U have been invited to join #pug.up"
+			echo "/msg $1 $COLBOLD In order to keep unwanted people out, #pug.up is an invite-only channel."
+			echo "/msg $1 $COLBOLD If you are authed atm i registered u to the channel for trial."
+			echo "/msg $1 $COLBOLD From now on u can invite urself to the pug channel with the following commands:"
+			echo "/msg $1 $COLRED$COLBOLD /msg Q invite #pug.up"
+			echo "/msg $1 $COLBOLD /join #pug.up"
+			echo "/msg $1 $COLBOLD Alternatively, you can set your own +j flag on the channel, which will cause you to be auto-invited whenever you auth: /msg Q chanlev #pug.up $1 +j"
+			echo "/msg $1 $COLBOLD If you need an auth account, then you need to type: /msg Q HELLO <your_email> <your_email>"
+			echo "/msg $1 $COLBOLD If i failed to register u properly contact the admins for support: BADMF, amok, teasy, tomy, nogginbasher"
+			echo "/msg $1 $COLGREEN$COLBOLD Enjoy puggin !"
+			echo "$COLPINK ... done"
+			exit
+		fi
+
+		echo "/invite $1 #pug.up"
+		echo "$COLRESET I have invited $COLRED$COLBOLD $1 $COLRESET to #pug.up"
+		echo "$COLPINK Sending Explanation to $COLRED$COLBOLD $1 $COLPINK..."
+		echo "/msg $1 $COLBOLD U have been invited to join #pug.up"
+		echo "/msg $1 $COLBOLD In order to keep unwanted people out, #pug.up is an invite-only channel."
+		echo "/msg $1 $COLBOLD Make sure to read the rules, be nice and enjoy puggin !"
+		echo "$COLPINK ... done"  
+		exit
+
+	) | double_escape_slashes
+
+	## We always exit in this channel.  Teasy doesn't want to see the other commands.
 	exit
-	fi
 
-        if [ "$2" = "register" ]
-        then
-            echo "/msg Q chanlev #pug.up $1 +gv"
-            echo "$COLRESET I have invited $COLRED$COLBOLD $1 $COLRESET to #pug.up and also attempted to $COLBOLD register $COLRESET him with +gv"
-            echo "/invite $1 #pug.up"
-            echo "$COLPINK Sending Explanation to $COLRED$COLBOLD $1 $COLPINK..."
-            echo "/msg $1 $COLBOLD U have been invited to join #pug.up"
-            echo "/msg $1 $COLBOLD In order to keep unwanted people out, #pug.up is an invite-only channel."
-            echo "/msg $1 $COLBOLD If you are authed atm i registered u to the channel with +gv."
-            echo "/msg $1 $COLBOLD From now on u can invite urself to the pug channel with the following commands:"
-            echo "/msg $1 $COLRED$COLBOLD /msg Q invite #pug.up"
-            echo "/msg $1 $COLBOLD /join #pug.up"
-            echo "/msg $1 $COLBOLD Alternatively, you can set your own +j flag on the channel, which will cause you to be auto-invited whenever you auth: /msg Q chanlev #pug.up $1 +j"
-            echo "/msg $1 $COLBOLD If you need an auth account, then you need to type: /msg Q HELLO <your_email> <your_email>"
-            echo "/msg $1 $COLBOLD If i failed to register u properly contact the admins for support: BADMF, amok, teasy, tomy, nogginbasher"
-            echo "/msg $1 $COLGREEN$COLBOLD Enjoy puggin !"
-	    echo "$COLPINK ... done"
-        exit
-        fi
-
-        if [ "$2" = "trial" ]
-        then
-            echo "/msg Q chanlev #pug.up $1 +k"
-            echo "$COLRESET I have invited $COLRED$COLBOLD $1 $COLRESET to #pug.up and also attempted to $COLBOLD register $COLRESET him as $COLGREEN$COLBOLD trial $COLRESET with +k"
-            echo "/invite $1 #pug.up"
-            echo "$COLPINK Sending Explanation to $COLRED$COLBOLD $1 $COLPINK..."
-            echo "/msg $1 $COLBOLD U have been invited to join #pug.up"
-            echo "/msg $1 $COLBOLD In order to keep unwanted people out, #pug.up is an invite-only channel."
-            echo "/msg $1 $COLBOLD If you are authed atm i registered u to the channel for trial."
-            echo "/msg $1 $COLBOLD From now on u can invite urself to the pug channel with the following commands:"
-            echo "/msg $1 $COLRED$COLBOLD /msg Q invite #pug.up"
-            echo "/msg $1 $COLBOLD /join #pug.up"
-            echo "/msg $1 $COLBOLD Alternatively, you can set your own +j flag on the channel, which will cause you to be auto-invited whenever you auth: /msg Q chanlev #pug.up $1 +j"
-            echo "/msg $1 $COLBOLD If you need an auth account, then you need to type: /msg Q HELLO <your_email> <your_email>"
-            echo "/msg $1 $COLBOLD If i failed to register u properly contact the admins for support: BADMF, amok, teasy, tomy, nogginbasher"
-            echo "/msg $1 $COLGREEN$COLBOLD Enjoy puggin !"
-	    echo "$COLPINK ... done"
-
-        exit
-        fi
-
-            echo "/invite $1 #pug.up"
-            echo "$COLRESET I have invited $COLRED$COLBOLD $1 $COLRESET to #pug.up"
-            echo "$COLPINK Sending Explanation to $COLRED$COLBOLD $1 $COLPINK..."
-            echo "/msg $1 $COLBOLD U have been invited to join #pug.up"
-            echo "/msg $1 $COLBOLD In order to keep unwanted people out, #pug.up is an invite-only channel."
-            echo "/msg $1 $COLBOLD Make sure to read the rules, be nice and enjoy puggin !"
-            echo "$COLPINK ... done"  
-        exit
 fi
-) | double_escape_slashes
 
 # if [ ! "$CHANNEL" = "#noobpug" ]
 # then
@@ -132,9 +175,9 @@ fi
 	# exit 0
 # fi
 
-if [ ! "$CHANNEL" = "#noobpug" ] && [ "$*" ]
-then echo "/invite $1 #noobpug"
-fi
+# if [ ! "$CHANNEL" = "#noobpug" ] && [ "$*" ]
+# then echo "/invite $1 #noobpug"
+# fi
 
 if [ "$CHANNEL" = "#noobpug" ] # || [ "$CHANNEL" = "#ut" ]
 then
@@ -158,7 +201,10 @@ then
 
 else
 
-	echo "/notice $NICK My !invite command is not enabled in this channel.  Perhaps you wanted: !invitebot #your_channel"
+	if [ ! "$CHANNEL" = "#ctf.pug" ]
+	then
+		echo "/notice $NICK My !invite command is not enabled in this channel.  Perhaps you wanted: !invitebot #your_channel"
+	fi
 
 fi
 
diff --git a/irc/xchat_sh_plugin/xchat_sh_scripts/scanpug/scanlastpug b/irc/xchat_sh_plugin/xchat_sh_scripts/scanpug/scanlastpug
--- a/irc/xchat_sh_plugin/xchat_sh_scripts/scanpug/scanlastpug
+++ b/irc/xchat_sh_plugin/xchat_sh_scripts/scanpug/scanlastpug
@@ -1,7 +1,7 @@
 ## TODO: This has to do a lot of work scanning auths whenever someone does !list
 ##       It would be better just to check whether the most recent list == the last scanned list, *before* doing the auth scanning.  :P
 
-if [ "$CHANNEL" = "#ut.pug" ] || [ "$CHANNEL" = "#noobpug" ] || [ "$CHANNEL" = "#siegepug" ] || [ "$CHANNEL" = "#pug.up" ] || [ "$CHANNEL" = "#ut994funpug" ] || [ "$CHANNEL" = "#pug" ]
+if [ "$CHANNEL" = "#ut.pug" ] || [ "$CHANNEL" = "#noobpug" ] || [ "$CHANNEL" = "#siegepug" ] || [ "$CHANNEL" = "#pug.up" ] || [ "$CHANNEL" = "#ut994funpug" ] || [ "$CHANNEL" = "#pug" ] || [ "$CHANNEL" = "#ctf.pug" ] || [ "$CHANNEL" = "#tehpugz" ]
 then
 
 	(
@@ -11,11 +11,11 @@ then
 	mkdir -p ~/.scanpug
 	LASTLINES=`cat ~/.scanpug/$CHANNEL-last.lines`
 	LASTDATA=`cat ~/.scanpug/$CHANNEL-last.picks`
-	LINES=`sh scanpug/lastrivalpicks -lines`
+	LINES=`bash scanpug/lastrivalpicks -lines`
 	if [ ! "$LINES" ]
 	then
 		jshwarn "Failed to get LINES"
-		echo "/msg nogginBasher Failed to get LINES in $CHANNEL"
+		[ "$CHANNEL" = "#tehpugz" ] || echo "/msg nogginBasher Failed to get LINES in $CHANNEL"
 		exit 0
 	fi
 	if [ "$LINES" = "$LASTLINES" ]
@@ -23,7 +23,7 @@ then
 		jshinfo "We have already scanned this pug."
 		exit 0
 	fi
-	DATA=`sh scanpug/lastrivalpicks`
+	DATA=`bash scanpug/lastrivalpicks`
 	# echo "$DATA" | grep -v "\.users\.quakenet\.org" | takecols 3 |
 	# while read NOTAUTHED
 	# do echo "/whois $NOTAUTHED"
@@ -33,7 +33,7 @@ then
 		BAD_COUNT=`echo "$DATA" | grep -c "DUNNO_AUTH"`
 		if [ "$BAD_COUNT" -gt 5 ]
 		then
-			echo "/msg nogginBasher Error! Failed attempt to parse $CHANNEL pickup stats: $MINIREPORT"
+			echo "/msg nogginBasher Error! Too many auth failures to update $CHANNEL pickup stats."
 		else
 			## OK go ahead and save the data.
 			echo "$LINES" > ~/.scanpug/"$CHANNEL-last.lines"
diff --git a/irc/xchat_sh_plugin/xchat_sh_scripts/servers_by_name/nwctf b/irc/xchat_sh_plugin/xchat_sh_scripts/servers_by_name/nwctf
--- a/irc/xchat_sh_plugin/xchat_sh_scripts/servers_by_name/nwctf
+++ b/irc/xchat_sh_plugin/xchat_sh_scripts/servers_by_name/nwctf
@@ -19,37 +19,59 @@ fi
 
 # (
 
+originalArgs="$*"
+
+do_batch() {
+
+	(
+		export NOTICE_STYLE="none"
+		# jshinfo "Doing batch: $*"
+		# Now closed: Multiplay CTF 85.236.100.43 p 195.4.17.197 
+		for SERVER in "$@"
+		## DOWN afaik: tits oldpmp bmb be sahne il whore relax dk fraggerspub
+		## now MH: smo
+		# 82.192.78.54:7000 ## -ev!L~eLves-
+		do
+			# jshinfo "Doing server: $SERVER"
+			[ -x ./ut_servers/"$SERVER" ] && ./ut_servers/"$SERVER" $JUSTSERVER $originalArgs || ./utp $JUSTSERVER $originalArgs "$SERVER"
+		done
+		## TODO: if we *always* grep for CTF- then we can include any servers which might or might not be in CTF mode
+		## TODO: could also grep -v CTF-Face and then include some mainly-Face servers
+	) |
+
+	if [ "$ALL" ]
+	# then cat
+	then NOTICE_STYLE="msg" notice
+	else
+		grep --line-buffered "CTF-" |
+		grep --line-buffered -v " 0/" |
+		grep --line-buffered -v "\(DOWN\|no response\)"
+	fi
+	# sort -n -r -k 2 | ## Not working for 10+
+	# grep . || echo "None of the servers are populated right now.  Try !xol !ffa !focr or !terror :P"
+
+	# ) |
+	# 
+	# if [ "$ALL" ]
+	# then notice
+	# else cat
+	# fi
+
+}
+
+## Despite all effots above, the results are not displayed until an entire
+#batch has finished.  So we do two batches:
+
 (
-	export NOTICE_STYLE="none"
-	# Now closed: Multiplay CTF 85.236.100.43 p 195.4.17.197 
-	for SERVER in xol of inz u hh2 kx syn synlin cod dn tacsu f0x nzp $OTHERS terror kawa f0x2 # gla nd focr nzp noobpug ## (multiplay FFA DM+CTF) # inf zooz 
-	## DOWN afaik: tits oldpmp bmb be sahne il whore relax dk fraggerspub
-	## now MH: smo
-	# 82.192.78.54:7000 ## -ev!L~eLves-
-	do [ -x ./ut_servers/"$SERVER" ] && ./ut_servers/"$SERVER" $JUSTSERVER "$@" || ./utp $JUSTSERVER "$@" "$SERVER"
-	done
-	## TODO: if we *always* grep for CTF- then we can include any servers which might or might not be in CTF mode
-	## TODO: could also grep -v CTF-Face and then include some mainly-Face servers
+	## Should exist and respond quickly:
+	do_batch xol u hh2 nzp syn judge
+
+	## Takes ages to respond:
+	do_batch of inz terror synlin cod dn tacsu f0x kx $OTHERS latina kawa f0x2 trek 94.75.249.199 #zeit # gla nd focr nzp noobpug ## (multiplay FFA DM+CTF) # inf zooz 
 ) |
 
-if [ "$ALL" ]
-# then cat
-then NOTICE_STYLE="msg" notice
-else
-	grep --line-buffered "CTF-" |
-	grep --line-buffered -v " 0/" |
-	grep --line-buffered -v "\(DOWN\|no response\)"
-fi |
-# sort -n -r -k 2 | ## Not working for 10+
-# grep . || echo "None of the servers are populated right now.  Try !xol !ffa !focr or !terror :P"
 grep --line-buffered . ||
 # echo "No nwCTF servers have players right now.  (If I missed any, please PM me!)"
 # echo "No nwCTF servers have players right now (except maybe !xol !ffa or !ec).  (Use -all to see the full list, and if I missed any, please PM nogginBasher!)"
-echo "I searched all the normal weapons CTF servers I know and found none populated.  To see the list add -all, or try !ctf or !nwctf2.  /msg nB^ if you find a new ip!"
+echo "I searched all the normal weapons CTF servers I know and found none populated.  To see the list add -all, or try !ctf or !nwctf2.  /msg nogginBasher if you find a new ip!"
 
-# ) |
-# 
-# if [ "$ALL" ]
-# then notice
-# else cat
-# fi
diff --git a/irc/xchat_sh_plugin/xchat_sh_scripts/wordgame/guess b/irc/xchat_sh_plugin/xchat_sh_scripts/wordgame/guess
--- a/irc/xchat_sh_plugin/xchat_sh_scripts/wordgame/guess
+++ b/irc/xchat_sh_plugin/xchat_sh_scripts/wordgame/guess
@@ -1,4 +1,6 @@
-if [ "$CHANNEL" = "#xoldog" ]
+#!/bin/bash
+
+if [ "$CHANNEL" = "#ut.pug" ]   # || [ "$CHANNEL" = "#xoldog" ]
 then
 	echo "Spam in #wordgame ;)"
 	exit 0
@@ -10,6 +12,10 @@ fi
 . wordgame/wordgame.shlib
 
 [ "$NICK" ] || NICK=nogginb0t
+
+# if [ "$NICK" = "sy\`" ]
+# then echo "Malfunction." ; exit 0
+# fi
 
 remove_letter () {
 	LETTER_TO_REMOVE="$1"
@@ -81,15 +87,25 @@ do
 
 		## Check to see if the word exists!
 
-		DICT_RESULT=` dict -d wn "$WORD" 2>&1 `
+		# BUG: When utb0t was blocked from hwi by firewall, it caused a very slow
+		# timeout.  Without locking on !guess, this could enable 1 person to score
+		# multiple times by calling !guess in parallel.
+		## -d wn because WordNet gives better definitions
+		DICT_RESULT=` which dict >/dev/null 2>&1 && dict -d wn "$WORD" 2>&1 `
+		if [ ! "$?" = 0 ]
+		then jshinfo "Error code on DICT_RESULT=$DICT_RESULT so emptying it"
+			DICT_RESULT=""
+		fi
+		# Some ovserved dict exit codes: 20 no definition, 21 suggestions
+		# Any other codes may suggest an actual error!
 
 		# echo "dict -d wn \"$WORD\" returned error-code $?" >&2
 
-		if ! echo "$DICT_RESULT" | head -n 1 | grep "^No definition" >/dev/null
+		if ! [ "$DICT_RESULT" = "" ] && ! echo "$DICT_RESULT" | head -n 1 | grep "^No definition" >/dev/null && ! echo "$DICT_RESULT" | grep "^dict: Access to server .* denied" >/dev/null
 		then
 			SHORT_DEFINITION=` echo "$DICT_RESULT" | takeline 6 | beforefirst ";" | sed 's+^[ 	]*++' `
 			# [ "$THIS_WORD_FAILED" ] && EXTRA= || EXTRA=" $COLGREY($NICK gets $COLGREEN$POINTS_FOR_WORD$COLGREY points!)"
-			FOUND_WORDS="$FOUND_WORDS$COLYELLOW$WORD$COLGREY: $COLBLUE$COLBOLD$SHORT_DEFINITION$COLRESET$EXTRA " # ($COLGREY!dict $WORD for more)"
+			FOUND_WORDS="$FOUND_WORDS$COLYELLOW$WORD$COLGREY: $COLROYAL$SHORT_DEFINITION$COLRESET$EXTRA " # ($COLGREY!dict $WORD for more)"
 			# GOT_ONE=true
 			## THIS_WORD_FAILED == "" and TOSHOW definitely has something
 		else
@@ -98,7 +114,7 @@ do
 			# if cat $DICTIONARY_FILES | extract_legal_words | grep -i "^$WORD$" >/dev/null
 			if list_answers | grep -i "^$WORD$" >/dev/null
 			then
-				FOUND_WORDS="$FOUND_WORDS$COLYELLOW$WORD$COLGREY: $COLBLUE$COLBOLD[No definition]$COLRESET "
+				FOUND_WORDS="$FOUND_WORDS$COLYELLOW$WORD$COLGREY: $COLROYAL[No definition]$COLRESET "
 				# GOT_ONE=true
 				## THIS_WORD_FAILED == "" and TOSHOW definitely has something
 			else
@@ -111,17 +127,29 @@ do
 		if [ ! "$THIS_WORD_FAILED" ]
 		then
 			POINTS_FOR_WORD=$((NUM_LETTERS-3))
-			# echo "$COLGREEN$POINTS_FOR_WORD$COLGREY points for $COLRED$WORD$COLGREY: $COLBLUE$COLBOLD$SHORT_DEFINITION$COLGREY"
+			# echo "$COLGREEN$POINTS_FOR_WORD$COLGREY points for $COLRED$WORD$COLGREY: $COLROYAL$SHORT_DEFINITION$COLGREY"
 			increase_score "$NICK" "$POINTS_FOR_WORD"
 			# echo "$COLGREY$NICK gets $COLGREEN$SCORE_TO_ADD$COLGREY points, for a total of $COLGREEN$CURRENT_SCORE$COLGREY!"
 			echo "$WORD was already guessed by $NICK :P" | tolowercase >> "$GUESSED_FILE"
 			# now done by increase_score: CURRENT_SCORE=$((CURRENT_SCORE+SCORE_TO_ADD))
 			SCORE_SUM="$SCORE_SUM $COLGREY+$COLGREEN$SCORE_TO_ADD"
 
-			if [ "$NUM_LETTERS" = "$TOTAL_NUM_LETTERS" ] && [ "$NUM_LETTERS" -gt 8 ] ## only for 9-letter words or longer
+			if [ "$NUM_LETTERS" = "$TOTAL_NUM_LETTERS" ]
 			then
-				increase_score "$NICK" "10"
-				SCORE_SUM="$SCORE_SUM $COLGREY+$COLORANGE""10 for using all the letters!"
+				touch "$COMPLETED_ROUND_FILE"
+				if [ "$NUM_LETTERS" -gt 5 ] ## only reward for 6-letter words or longer
+				then
+					if [ "$NUM_LETTERS" -lt 7 ]
+					then INC=1
+					elif [ "$NUM_LETTERS" -lt 8 ]
+					then INC=2
+					elif [ "$NUM_LETTERS" -lt 9 ]
+					then INC=5
+					else INC=10
+					fi
+					increase_score "$NICK" "$INC"
+					SCORE_SUM="$SCORE_SUM $COLGREY+$COLORANGE""$INC for using all the letters!"
+				fi
 			fi
 
 			if [ "$NICK" = "[A]Melted_Ice" ] && [ `seq 1 5 | chooserandomline` = 1 ]
@@ -132,10 +160,10 @@ do
 
 			SO_FAR=$((SO_FAR+1))
 
-			if [ $((TOTAL-SO_FAR)) -lt 10 ] && [ "$TOTAL_NUM_LETTERS" -gt 6 ] ## bonus only for wordgames with 7 or more letters
+			if [ $((TOTAL-SO_FAR)) -lt 10 ] && [ "$TOTAL_NUM_LETTERS" -gt 6 ] && [ "$TOTAL" -gt 19 ] ## final countdown bonus only for wordgames with 7 or more letters, and 20 or more answers
 			then
 				# BONUS=$(((10-TOTAL+SO_FAR)*10))
-				BONUS=$((10-TOTAL+SO_FAR))
+				BONUS=$(( (10-TOTAL+SO_FAR)/2 ))
 				increase_score "$NICK" "$BONUS"
 				SCORE_SUM="$SCORE_SUM $COLGREY+$COLORANGE"" bonus $BONUS"
 			fi
