first parse of spiral.d!

diff --git a/java/tools/parser/creategrammar b/java/tools/parser/creategrammar
--- a/java/tools/parser/creategrammar
+++ b/java/tools/parser/creategrammar
@@ -5,10 +5,13 @@ name="$1"
 cd src/tools/parser || exit 3
 
 mv "$1Grm.java" "$1Grm.java.b4create"
-(
-	# echo "package tools.parser;"
-	jparse grm "$1.grm" java $2 $3 $4 $5 $6
-) > "$1Grm.java"
+# echo "package tools.parser;"
+jparse grm "$1.grm" java $2 $3 $4 $5 $6 > "$1Grm.java"
+if [ ! "$?" = 0 ]
+then
+	echo "jparse failed - not trying to compile."
+	exit 4
+fi
 #mv "$1Grm.java" tmp.txt
 #mv tmp.txt "$1Grm.java"
 sedreplace "grmGrm" "$1Grm" "$1Grm.java"
@@ -16,5 +19,15 @@ jfcsh "$1Grm.java.b4create" "$1Grm.java"
 
 cd ../../..
 
-./build.sh
+# ./build.sh
+cd src
+javac tools/parser/"$1Grm.java"
+success="$?"
+if [ "$success" ]
+then
+	mv -f tools/parser/"$1Grm.class" ../bin/tools/parser/"$1Grm.class"
+else
+	echo "Failed to compile the new ruleset!"
+	exit 6
+fi
 
